<a href="https://colab.research.google.com/github/harshadbabar26-dev/HB1/blob/main/Convolution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Total zeros: 10


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
from PIL import Image

# Step 1: Upload image
uploaded = files.upload()

# Step 2: Get uploaded file name
image_name = list(uploaded.keys())[0]

# Step 3: Open image
img = Image.open(image_name)

# Step 4: Convert to numpy array (matrix)
img_matrix = np.array(img)

# Step 5: Print matrix
print("Image Matrix Shape:", img_matrix.shape)
print(img_matrix)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
from PIL import Image

# ===============================
# STEP 1: Upload Image
# ===============================
uploaded = files.upload()
image_name = list(uploaded.keys())[0]

# ===============================
# STEP 2: Convert Image to Grayscale
# ===============================
img = Image.open(image_name).convert("L")

# Convert image to numpy matrix
img_matrix = np.array(img)

print("Original Image Shape:", img_matrix.shape)

# ===============================
# STEP 3: Define 2x2 Convolution Kernel
# ===============================
# This is a simple averaging kernel
kernel = np.array([[1, 1],
                   [1, 1]])

# Normalize kernel (optional but recommended)
kernel = kernel / 4

print("Kernel:\n", kernel)

# ===============================
# STEP 4: Perform Convolution (No Padding)
# ===============================
h, w = img_matrix.shape

# We reduce size by 1 because 2x2 kernel
output_height = h - 1
output_width = w - 1

conv_output = np.zeros((output_height, output_width))

# Sliding window
for i in range(output_height):
    for j in range(output_width):

        # Extract 2x2 region
        region = img_matrix[i:i+2, j:j+2]

        # Element-wise multiplication
        conv_value = np.sum(region * kernel)

        # Store result
        conv_output[i, j] = conv_value

print("Convolution Output Shape:", conv_output.shape)

# ===============================
# STEP 5: Apply Activation Function
# ===============================
# Example: ReLU (Rectified Linear Unit)
# ReLU(x) = max(0, x)

relu_output = np.maximum(0, conv_output)

# ===============================
# STEP 6: Reduce to ONE Final Number
# ===============================
# Example: Take mean of entire convolved matrix

final_number = np.mean(relu_output)

print("Final Single Output Number:", final_number)

Saving mighty-beautiful-lion-resting-african-savannah-black-white-kenya-96042281.webp to mighty-beautiful-lion-resting-african-savannah-black-white-kenya-96042281 (2).webp
Original Image Shape: (524, 800)
Kernel:
 [[0.25 0.25]
 [0.25 0.25]]
Convolution Output Shape: (523, 799)
Final Single Output Number: 119.60764172232498


In [ ]:
import numpy as np
from google.colab import files
from PIL import Image

# Upload image
uploaded = files.upload()
image_name = list(uploaded.keys())[0]

# Convert image to grayscale matrix
img = Image.open(image_name).convert("L")
img_matrix = np.array(img)

# Define kernel [0 1; 0 1]
kernel = np.array([[0, 1],
                   [0, 1]])

# Get image dimensions
h, w = img_matrix.shape

# Output matrix size (no padding, stride=1)
conv_output = np.zeros((h-1, w-1))

# Apply convolution
for i in range(h-1):
    for j in range(w-1):
        region = img_matrix[i:i+2, j:j+2]
        conv_output[i, j] = np.sum(region * kernel)

# Print convolution output matrix
print("Convolution Output Matrix:\n")
print(conv_output)

Saving mighty-beautiful-lion-resting-african-savannah-black-white-kenya-96042281.webp to mighty-beautiful-lion-resting-african-savannah-black-white-kenya-96042281 (4).webp
Convolution Output Matrix:

[[221. 214. 206. ... 204. 204. 204.]
 [210. 204. 199. ... 204. 204. 204.]
 [200. 194. 193. ... 204. 204. 204.]
 ...
 [ 80. 100.  74. ... 195. 194. 193.]
 [ 86.  97. 106. ... 191. 182. 176.]
 [ 92.  95. 106. ... 188. 172. 159.]]


In [ ]:
import numpy as np
from google.colab import files
from PIL import Image

# Upload image
uploaded = files.upload()
image_name = list(uploaded.keys())[0]

# Convert image to grayscale matrix
img = Image.open(image_name).convert("L")
img_matrix = np.array(img)

# Define kernel [0 1; 0 1]
kernel = np.array([[0, 1],
                   [0, 1]])

# Get image dimensions
h, w = img_matrix.shape

# Output matrix size (no padding, stride=1)
conv_output = np.zeros((h-1, w-1))

# Apply convolution
for i in range(h-1):
    for j in range(w-1):
        region = img_matrix[i:i+2, j:j+2]
        conv_output[i, j] = np.sum(region * kernel)

# Convert output matrix into single number
final_number = np.mean(conv_output)

print("Final Single Number:", final_number)

Saving mighty-beautiful-lion-resting-african-savannah-black-white-kenya-96042281.webp to mighty-beautiful-lion-resting-african-savannah-black-white-kenya-96042281 (5).webp
Final Single Number: 239.23774220643872
